"""empty message

Revision ID: 077e21e45317
Revises: c9dc674bd9e1
Create Date: 2019-08-01 16:28:06.935873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '077e21e45317'
down_revision = 'c9dc674bd9e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'switch_flag', 'switches', ['switch_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###

