"""empty message

Revision ID: 144e35d5d48c
Revises: edd2e8b01c23
Create Date: 2019-08-29 00:02:33.641014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '144e35d5d48c'
down_revision = 'edd2e8b01c23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switch_panel', sa.Column('panel_type', sa.SmallInteger(), nullable=True))
    op.drop_column('switches', 'control_type')
    op.drop_column('switches', 'level')
    # ### end Alembic commands ###


