"""empty message

Revision ID: 294bff88c79c
Revises: b92c21d051e0
Create Date: 2019-08-14 12:10:43.411349

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '294bff88c79c'
down_revision = 'b92c21d051e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ir_sensors', sa.Column('tcp_config_id', sa.Integer(), nullable=True))
    op.drop_constraint('ir_sensors_ibfk_2', 'ir_sensors', type_='foreignkey')
    op.create_foreign_key(None, 'ir_sensors', 'tcp_config', ['tcp_config_id'], ['id'], ondelete='SET NULL')
    op.drop_column('ir_sensors', 'ip_config_id')
