"""empty message

Revision ID: 2e4cc79a1dce
Revises: c792f221366e
Create Date: 2019-08-23 15:56:12.446464

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2e4cc79a1dce'
down_revision = 'c792f221366e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auto_controllers', sa.Column('tcp_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'auto_controllers', 'tcp_config', ['tcp_config_id'], ['id'], ondelete='set null')
    op.add_column('switch_panel', sa.Column('tcp_config_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'switch_panel', 'tcp_config', ['tcp_config_id'], ['id'], ondelete='set null')
    op.drop_column('switch_panel', 'ip')


