"""change length of external_id of uni_alarm

Revision ID: 3198b4c7dc98
Revises: c30c34e0c006
Create Date: 2020-01-09 17:39:22.909702

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3198b4c7dc98'
down_revision = 'c30c34e0c006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uni_alarms', 'external_id',
               existing_type=mysql.VARCHAR(length=30),
               type_=sa.Unicode(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uni_alarms', 'external_id',
               existing_type=sa.Unicode(length=100),
               type_=mysql.VARCHAR(length=30),
               existing_nullable=True)
    # ### end Alembic commands ###
