"""empty message

Revision ID: 36df34b30986
Revises: 5c53f0d2ecfd
Create Date: 2019-09-04 11:54:46.600327

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36df34b30986'
down_revision = '5c53f0d2ecfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('relay', sa.Column('addr', sa.Integer(), nullable=True))
    op.add_column('air_conditioner', sa.Column('temp', sa.Float(), nullable=True))
    op.add_column('air_conditioner', sa.Column('hum', sa.Float(), nullable=True))
    op.add_column('air_conditioner', sa.Column('mode', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relay', 'addr')
    op.drop_column('air_conditioner', 'hum')
    op.drop_column('air_conditioner', 'temp')
    op.drop_column('air_conditioner', 'mode')
    # ### end Alembic commands ###
