"""add eco_mode to locators table

Revision ID: 37c51c7deec0
Revises: 673eaa1771e4
Create Date: 2020-01-06 15:52:54.559541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37c51c7deec0'
down_revision = '673eaa1771e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locators', sa.Column('eco_mode', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locators', 'eco_mode')
    # ### end Alembic commands ###
