"""empty message

Revision ID: 45360231ecf8
Revises: e2f86582b702
Create Date: 2019-07-11 14:50:44.305217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45360231ecf8'
down_revision = 'e2f86582b702'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locators',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('internal_code', sa.Unicode(length=50), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('zone', sa.Integer(), nullable=True),
    sa.Column('coorX', sa.Float(), nullable=True),
    sa.Column('coorY', sa.Float(), nullable=True),
    sa.Column('coorZ', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('internal_code')
    )

    op.create_table('users',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Unicode(length=50), nullable=True),
    sa.Column('job_no', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.SmallInteger(), nullable=True),
    sa.Column('org_path', sa.String(length=50), nullable=True),
    sa.Column('org_index_code', sa.String(length=50), nullable=True),
    sa.Column('org_name', sa.String(length=50), nullable=True),
    sa.Column('certificate_type', sa.Integer(), nullable=True),
    sa.Column('certificate_no', sa.String(length=50), nullable=True),
    sa.Column('phone_no', sa.String(length=30), nullable=True),
    sa.Column('address', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('education', sa.SmallInteger(), nullable=True),
    sa.Column('nation', sa.SmallInteger(), nullable=True),
    sa.Column('photo_url', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_person_id'), 'users', ['person_id'], unique=False)
    
    op.create_table('tracking_devices',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_index_code', sa.Unicode(length=50), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('locator', sa.Unicode(length=50), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('device_type', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['locator'], ['locators.internal_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracking_devices_device_index_code'), 'tracking_devices', ['device_index_code'], unique=False)


    op.create_table('appear_records',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['tracking_devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    

    op.create_table('aqi_sensors',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_index_code', sa.Unicode(length=50), nullable=True),
    sa.Column('locator', sa.Unicode(length=50), nullable=True),
    sa.Column('latest_record_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['locator'], ['locators.internal_code'], ondelete='SET NULL')
    )
    op.create_index(op.f('ix_aqi_sensors_device_index_code'), 'aqi_sensors', ['device_index_code'], unique=False)

    op.create_table('aqi_values',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('co2', sa.Float(), nullable=True),
    sa.Column('tvoc', sa.Float(), nullable=True),
    sa.Column('voc', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_foreign_key("fk_sensor_value", "aqi_values", "aqi_sensors",
                          ["sensor_id"], ["id"], ondelete='CASCADE')
    op.create_foreign_key("fk_latest_record_sensor", "aqi_sensors", "aqi_values",
                          ["latest_record_id"], ["id"], ondelete="SET NULL")
    
    op.create_table('circuit_breakers',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.Unicode(length=50), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('locator', sa.Unicode(length=50), nullable=True),
    sa.Column('room', sa.String(length=30), nullable=True),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['locator'], ['locators.internal_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    

    op.create_table('circuit_alarms',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker_id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.Integer(), nullable=True),
    sa.Column('node', sa.String(length=30), nullable=True),
    sa.Column('info', sa.String(length=30), nullable=True),
    sa.Column('type_number', sa.SmallInteger(), nullable=True),
    sa.Column('alarm_type', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['circuit_breaker_id'], ['circuit_breakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_circuit_breakers_mac'), 'circuit_breakers', ['mac'], unique=False)

    op.create_table('circuit_records',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker_id', sa.Integer(), nullable=True),
    sa.Column('addr', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=30), nullable=True),
    sa.Column('validity', sa.BOOLEAN(), nullable=True),
    sa.Column('enable_netctr', sa.BOOLEAN(), nullable=True),
    sa.Column('oc', sa.BOOLEAN(), nullable=True),
    sa.Column('online', sa.BOOLEAN(), nullable=True),
    sa.Column('total_power', sa.Float(), nullable=True),
    sa.Column('mxgg', sa.Float(), nullable=True),
    sa.Column('mxgl', sa.Float(), nullable=True),
    sa.Column('line_type', sa.SmallInteger(), nullable=True),
    sa.Column('spec', sa.String(length=30), nullable=True),
    sa.Column('control', sa.BOOLEAN(), nullable=True),
    sa.Column('visibility', sa.BOOLEAN(), nullable=True),
    sa.Column('alarm', sa.Integer(), nullable=True),
    sa.Column('gLd', sa.Float(), nullable=True),
    sa.Column('gA', sa.Float(), nullable=True),
    sa.Column('gT', sa.Float(), nullable=True),
    sa.Column('gV', sa.Float(), nullable=True),
    sa.Column('gW', sa.Float(), nullable=True),
    sa.Column('gPF', sa.Float(), nullable=True),
    sa.Column('aA', sa.Float(), nullable=True),
    sa.Column('aT', sa.Float(), nullable=True),
    sa.Column('aV', sa.Float(), nullable=True),
    sa.Column('aW', sa.Float(), nullable=True),
    sa.Column('aPF', sa.Float(), nullable=True),
    sa.Column('bA', sa.Float(), nullable=True),
    sa.Column('bT', sa.Float(), nullable=True),
    sa.Column('bV', sa.Float(), nullable=True),
    sa.Column('bW', sa.Float(), nullable=True),
    sa.Column('bPF', sa.Float(), nullable=True),
    sa.Column('cA', sa.Float(), nullable=True),
    sa.Column('cT', sa.Float(), nullable=True),
    sa.Column('cV', sa.Float(), nullable=True),
    sa.Column('cW', sa.Float(), nullable=True),
    sa.Column('cPF', sa.Float(), nullable=True),
    sa.Column('nA', sa.Float(), nullable=True),
    sa.Column('nT', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_breaker_id'], ['circuit_breakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    
    op.create_table('elevators',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_index_code', sa.Unicode(length=50), nullable=True),
    sa.Column('locator', sa.Unicode(length=50), nullable=True),
    sa.ForeignKeyConstraint(['locator'], ['locators.internal_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_elevators_device_index_code'), 'elevators', ['device_index_code'], unique=False)


    op.create_table('elevator_status',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('elevator_id', sa.Integer(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['elevator_id'], ['elevators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )


    op.create_table('energy_consume_daily',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('consume_id', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker', sa.Integer(), nullable=True),
    sa.Column('addr', sa.Integer(), nullable=True),
    sa.Column('electricity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_breaker'], ['circuit_breakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consume_id')
    )


    op.create_table('energy_consume_monthly',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('consume_id', sa.Integer(), nullable=False),
    sa.Column('circuit_breaker', sa.Integer(), nullable=True),
    sa.Column('addr', sa.Integer(), nullable=True),
    sa.Column('electricity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_breaker'], ['circuit_breakers.id'], ),
    sa.PrimaryKeyConstraint('consume_id')
    )

    

    op.create_table('fire_alarm_sensors',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_index_code', sa.Unicode(length=50), nullable=True),
    sa.Column('locator', sa.Unicode(length=50), nullable=True),
    sa.Column('latest_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locator'], ['locators.internal_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fire_alarm_sensors_device_index_code'), 'fire_alarm_sensors', ['device_index_code'], unique=False)


    op.create_table('fire_alarm_status',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['fire_alarm_sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    
    op.create_foreign_key('fk_latest_status_fire_alarm', 'fire_alarm_sensors', 'fire_alarm_status', 
                          ['latest_record_id'], ['id'], ondelete="SET NULL")


    op.create_table('heatmap_snapshots',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['tracking_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    

    op.create_table('ir_sensor_status',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ir_sensors',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_index_code', sa.Unicode(length=50), nullable=True),
    sa.Column('locator', sa.Unicode(length=50), nullable=True),
    sa.Column('latest_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locator'], ['locators.internal_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ir_sensors_device_index_code'), 'ir_sensors', ['device_index_code'], unique=False)

    
    op.create_foreign_key("fk_ir_sensor_status", "ir_sensor_status", "ir_sensors",
                          ["sensor_id"], ["id"], ondelete='CASCADE')
    op.create_foreign_key("fk_latest_record_ir_sensor", "ir_sensors", "ir_sensor_status", 
                           ["latest_record_id"], ["id"], ondelete="SET NULL")

    

    op.create_table('latest_alarms',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('circuit_alarm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_alarm_id'], ['circuit_alarms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuit_breakers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latest_alarms_circuit_id'), 'latest_alarms', ['circuit_id'], unique=False)


    op.create_table('latest_circuit_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('circuit_id', sa.Integer(), nullable=True),
    sa.Column('circuit_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuit_breakers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['circuit_record_id'], ['circuit_records.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latest_circuit_record_circuit_id'), 'latest_circuit_record', ['circuit_id'], unique=False)
    

    op.create_table('lux_sensors',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_index_code', sa.Unicode(length=50), nullable=True),
    sa.Column('locator', sa.Unicode(length=50), nullable=True),
    sa.Column('latest_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locator'], ['locators.internal_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lux_sensors_device_index_code'), 'lux_sensors', ['device_index_code'], unique=False)
    op.create_table('lux_values',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    
    sa.ForeignKeyConstraint(['latest_record_id'], ['lux_values.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_id'], ['lux_sensors.id'], ondelete='CASCADE'),
    op.create_foreign_key('fk_latest_record_lux_sensor', 'lux_sensors', 'lux_values',
                          ['latest_record_id'], ['id'], ondelete="SET NULL")
    op.create_foreign_key('fk_lux_sensor_status', 'lux_values', 'lux_sensors',
                          ['sensor_id'], ['id'], ondelete='CASCADE')
    

    op.create_table('switches',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_index_code', sa.Unicode(length=50), nullable=True),
    sa.Column('locator', sa.Unicode(length=50), nullable=True),
    sa.Column('latest_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['locator'], ['locators.internal_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_switches_device_index_code'), 'switches', ['device_index_code'], unique=False)


    op.create_table('switch_status',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['switches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_foreign_key('fk_latest_record_switch', 'switches', 'switch_status',
                          ['latest_record_id'], ['id'], ondelete='SET NULL')
        
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_person_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tracking_devices_device_index_code'), table_name='tracking_devices')
    op.drop_table('tracking_devices')
    op.drop_index(op.f('ix_switches_device_index_code'), table_name='switches')
    op.drop_table('switches')
    op.drop_table('switch_status')
    op.drop_table('lux_values')
    op.drop_index(op.f('ix_lux_sensors_device_index_code'), table_name='lux_sensors')
    op.drop_table('lux_sensors')
    op.drop_table('locators')
    op.drop_index(op.f('ix_latest_circuit_record_circuit_id'), table_name='latest_circuit_record')
    op.drop_table('latest_circuit_record')
    op.drop_index(op.f('ix_latest_alarms_circuit_id'), table_name='latest_alarms')
    op.drop_table('latest_alarms')
    op.drop_index(op.f('ix_ir_sensors_device_index_code'), table_name='ir_sensors')
    op.drop_table('ir_sensors')
    op.drop_table('ir_sensor_status')
    op.drop_table('heatmap_snapshots')
    op.drop_table('fire_alarm_status')
    op.drop_index(op.f('ix_fire_alarm_sensors_device_index_code'), table_name='fire_alarm_sensors')
    op.drop_table('fire_alarm_sensors')
    op.drop_table('energy_consume_monthly')
    op.drop_table('energy_consume_daily')
    op.drop_index(op.f('ix_elevators_device_index_code'), table_name='elevators')
    op.drop_table('elevators')
    op.drop_table('elevator_status')
    op.drop_table('circuit_records')
    op.drop_index(op.f('ix_circuit_breakers_mac'), table_name='circuit_breakers')
    op.drop_table('circuit_breakers')
    op.drop_table('circuit_alarms')
    op.drop_table('aqi_values')
    op.drop_index(op.f('ix_aqi_sensors_device_index_code'), table_name='aqi_sensors')
    op.drop_table('aqi_sensors')
    op.drop_table('appear_records')
    # ### end Alembic commands ###
