"""empty message

Revision ID: 46d39fa3f25d
Revises: 562e7e5991a4
Create Date: 2019-07-12 16:18:18.358332

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46d39fa3f25d'
down_revision = '562e7e5991a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acs_records',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('acs_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('event_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['acs_id'], ['tracking_devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_logins',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Unicode(length=50), nullable=True),
    sa.Column('username', sa.Unicode(length=50), nullable=True),
    sa.Column('password', sa.String(length=50), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.person_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('switch_status', sa.Column('load', sa.Integer(), nullable=True))
    op.add_column('switches', sa.Column('channel', sa.Integer(), nullable=True))
    op.drop_column('tracking_devices', 'status')
    op.add_column('users', sa.Column('person_name', sa.Unicode(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'person_name')
    op.add_column('tracking_devices', sa.Column('status', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True))
    op.drop_column('switches', 'channel')
    op.drop_column('switch_status', 'load')
    op.drop_table('user_logins')
    op.drop_table('acs_records')
    # ### end Alembic commands ###
