"""remove s3fc20 record

Revision ID: 46ebceb73fbc
Revises: 552db984648c
Create Date: 2019-12-16 11:37:32.332459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '46ebceb73fbc'
down_revision = '552db984648c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('s3_fc20_ibfk_3', 's3_fc20', type_='foreignkey')
    op.drop_column('s3_fc20', 'latest_record_id')
    op.drop_table('s3_fc20_records')
    op.drop_constraint('mantunci_box_ibfk_3', 'mantunci_box', type_='foreignkey')
    op.drop_column('mantunci_box', 'latest_alarm_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('s3_fc20', sa.Column('latest_record_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('s3_fc20_ibfk_3', 's3_fc20', 's3_fc20_records', ['latest_record_id'], ['id'], ondelete='SET NULL')
    op.alter_column('notification', 'title',
               existing_type=sa.Unicode(length=50),
               type_=mysql.VARCHAR(charset='utf8', length=400),
               existing_nullable=True)
    op.add_column('mantunci_box', sa.Column('latest_alarm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('mantunci_box_ibfk_3', 'mantunci_box', 'box_alarms', ['latest_alarm_id'], ['id'], ondelete='SET NULL')
    op.create_table('s3_fc20_records',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('s3_fc20_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('validity', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('enable_netctr', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('oc', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('online', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('total_power', mysql.FLOAT(), nullable=True),
    sa.Column('mxgg', mysql.FLOAT(), nullable=True),
    sa.Column('mxgl', mysql.FLOAT(), nullable=True),
    sa.Column('line_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('spec', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('control', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visibility', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('alarm', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('gLd', mysql.FLOAT(), nullable=True),
    sa.Column('gA', mysql.FLOAT(), nullable=True),
    sa.Column('gT', mysql.FLOAT(), nullable=True),
    sa.Column('gV', mysql.FLOAT(), nullable=True),
    sa.Column('gW', mysql.FLOAT(), nullable=True),
    sa.Column('gPF', mysql.FLOAT(), nullable=True),
    sa.Column('aA', mysql.FLOAT(), nullable=True),
    sa.Column('aT', mysql.FLOAT(), nullable=True),
    sa.Column('aV', mysql.FLOAT(), nullable=True),
    sa.Column('aW', mysql.FLOAT(), nullable=True),
    sa.Column('aPF', mysql.FLOAT(), nullable=True),
    sa.Column('bA', mysql.FLOAT(), nullable=True),
    sa.Column('bT', mysql.FLOAT(), nullable=True),
    sa.Column('bV', mysql.FLOAT(), nullable=True),
    sa.Column('bW', mysql.FLOAT(), nullable=True),
    sa.Column('bPF', mysql.FLOAT(), nullable=True),
    sa.Column('cA', mysql.FLOAT(), nullable=True),
    sa.Column('cT', mysql.FLOAT(), nullable=True),
    sa.Column('cV', mysql.FLOAT(), nullable=True),
    sa.Column('cW', mysql.FLOAT(), nullable=True),
    sa.Column('cPF', mysql.FLOAT(), nullable=True),
    sa.Column('nA', mysql.FLOAT(), nullable=True),
    sa.Column('nT', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['s3_fc20_id'], ['s3_fc20.id'], name='s3_fc20_records_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
