"""add cancel time

Revision ID: 507273553149
Revises: 3198b4c7dc98
Create Date: 2020-01-10 10:03:45.500784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507273553149'
down_revision = '3198b4c7dc98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uni_alarms', sa.Column('cancel_time', sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uni_alarms', 'cancel_time')
    # ### end Alembic commands ###
