"""empty message

Revision ID: 55d9dea26d96
Revises: 144e35d5d48c
Create Date: 2019-08-29 00:20:03.295084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '55d9dea26d96'
down_revision = '144e35d5d48c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switch_panel', sa.Column('locator_id', sa.Unicode(length=50), nullable=True))
    op.create_foreign_key(None, 'switch_panel', 'locators', ['locator_id'], ['internal_code'], ondelete='SET NULL')
    op.drop_constraint('switches_ibfk_1', 'switches', type_='foreignkey')
    op.drop_column('switches', 'locator_id')
