"""remove box id and box relation in EnergyConsume

Revision ID: 5c4e6cd6140b
Revises: caffaf31fe2c
Create Date: 2019-12-12 13:58:00.994722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c4e6cd6140b'
down_revision = 'caffaf31fe2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('energy_consume_by_hour_ibfk_1', 'energy_consume_by_hour', type_='foreignkey')
    op.drop_column('energy_consume_by_hour', 'box_id')
    op.drop_constraint('energy_consume_daily_ibfk_1', 'energy_consume_daily', type_='foreignkey')
    op.drop_column('energy_consume_daily', 'box_id')
    op.drop_constraint('energy_consume_monthly_ibfk_1', 'energy_consume_monthly', type_='foreignkey')
    op.drop_column('energy_consume_monthly', 'box_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('energy_consume_monthly', sa.Column('box_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('energy_consume_monthly_ibfk_1', 'energy_consume_monthly', 'mantunci_box', ['box_id'], ['id'])
    op.add_column('energy_consume_daily', sa.Column('box_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('energy_consume_daily_ibfk_1', 'energy_consume_daily', 'mantunci_box', ['box_id'], ['id'], ondelete='CASCADE')
    op.add_column('energy_consume_by_hour', sa.Column('box_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('energy_consume_by_hour_ibfk_1', 'energy_consume_by_hour', 'mantunci_box', ['box_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
