"""empty message

Revision ID: 5c53f0d2ecfd
Revises: 8f6b120c5c5d
Create Date: 2019-08-30 15:42:55.670996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5c53f0d2ecfd'
down_revision = '8f6b120c5c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('box_alarms', sa.Column('time', sa.TIMESTAMP(), nullable=True))
    op.add_column('mantunci_box', sa.Column('locator_id', sa.Unicode(length=50), nullable=True))
    op.create_foreign_key(None, 'mantunci_box', 'locators', ['locator_id'], ['internal_code'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
