"""upgrade mantunci and switches

Revision ID: 6077cfbaa448
Revises: 077e21e45317
Create Date: 2019-08-21 17:41:54.922354

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6077cfbaa448'
down_revision = '077e21e45317'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auto_controllers',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('if_auto', sa.SmallInteger(), nullable=True),
    sa.Column('locator_id', sa.Unicode(length=50), nullable=True),
    sa.Column('ir_count', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['locator_id'], ['locators.internal_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mantunci_box',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mac', sa.Unicode(length=50), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('latest_alarm_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('box_alarms',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.Integer(), nullable=True),
    sa.Column('node', sa.String(length=50), nullable=True),
    sa.Column('alarm_or_type', sa.String(length=30), nullable=True),
    sa.Column('info', sa.String(length=50), nullable=True),
    sa.Column('type_number', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['mantunci_box.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s3_fc20',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('addr', sa.Integer(), nullable=True),
    sa.Column('desc', sa.Unicode(length=100), nullable=True),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('latest_record_id', sa.Integer(), nullable=True),
    sa.Column('measure_type', sa.SmallInteger(), nullable=True),
    sa.Column('locator_id', sa.Unicode(length=50), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['mantunci_box.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['locator_id'], ['locators.internal_code'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('s3_fc20_records',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('s3_fc20_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('validity', sa.BOOLEAN(), nullable=True),
    sa.Column('enable_netctr', sa.BOOLEAN(), nullable=True),
    sa.Column('oc', sa.BOOLEAN(), nullable=True),
    sa.Column('online', sa.BOOLEAN(), nullable=True),
    sa.Column('total_power', sa.Float(), nullable=True),
    sa.Column('mxgg', sa.Float(), nullable=True),
    sa.Column('mxgl', sa.Float(), nullable=True),
    sa.Column('line_type', sa.SmallInteger(), nullable=True),
    sa.Column('spec', sa.String(length=50), nullable=True),
    sa.Column('control', sa.BOOLEAN(), nullable=True),
    sa.Column('visibility', sa.BOOLEAN(), nullable=True),
    sa.Column('alarm', sa.Integer(), nullable=True),
    sa.Column('gLd', sa.Float(), nullable=True),
    sa.Column('gA', sa.Float(), nullable=True),
    sa.Column('gT', sa.Float(), nullable=True),
    sa.Column('gV', sa.Float(), nullable=True),
    sa.Column('gW', sa.Float(), nullable=True),
    sa.Column('gPF', sa.Float(), nullable=True),
    sa.Column('aA', sa.Float(), nullable=True),
    sa.Column('aT', sa.Float(), nullable=True),
    sa.Column('aV', sa.Float(), nullable=True),
    sa.Column('aW', sa.Float(), nullable=True),
    sa.Column('aPF', sa.Float(), nullable=True),
    sa.Column('bA', sa.Float(), nullable=True),
    sa.Column('bT', sa.Float(), nullable=True),
    sa.Column('bV', sa.Float(), nullable=True),
    sa.Column('bW', sa.Float(), nullable=True),
    sa.Column('bPF', sa.Float(), nullable=True),
    sa.Column('cA', sa.Float(), nullable=True),
    sa.Column('cT', sa.Float(), nullable=True),
    sa.Column('cV', sa.Float(), nullable=True),
    sa.Column('cW', sa.Float(), nullable=True),
    sa.Column('cPF', sa.Float(), nullable=True),
    sa.Column('nA', sa.Float(), nullable=True),
    sa.Column('nT', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['s3_fc20_id'], ['s3_fc20.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('energy_consume_by_hour',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('consume_id', sa.Integer(), nullable=False),
    sa.Column('box_id', sa.Integer(), nullable=True),
    sa.Column('s3_fc20_id', sa.Integer(), nullable=True),
    sa.Column('electricity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['box_id'], ['mantunci_box.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['s3_fc20_id'], ['s3_fc20.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('consume_id')
    )
    op.create_index(op.f('ix_mantunci_box_mac'), 'mantunci_box', ['mac'], unique=False)

    op.create_table('switch_panel',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('desc', sa.Unicode(length=100), nullable=True),
    sa.Column('ip', sa.Unicode(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # TODO
    #################
    op.drop_index('ix_circuit_breakers_mac', table_name='circuit_breakers')
    op.drop_constraint('latest_circuit_record_ibfk_1', 'latest_circuit_record', type_='foreignkey')
    op.drop_constraint('latest_circuit_record_ibfk_2', 'latest_circuit_record', type_='foreignkey')
    op.drop_index('ix_latest_circuit_record_circuit_id', table_name='latest_circuit_record')

    op.drop_constraint('latest_alarms_ibfk_1', 'latest_alarms', type_='foreignkey')
    op.drop_constraint('latest_alarms_ibfk_2', 'latest_alarms', type_='foreignkey')
    op.drop_index('ix_latest_alarms_circuit_id', table_name='latest_alarms')
    op.drop_constraint('energy_consume_daily_ibfk_1', 'energy_consume_daily', type_='foreignkey')
    op.drop_table("latest_circuit_record")
    op.drop_table('latest_alarms')
    op.drop_table('circuit_records')
    op.drop_column('energy_consume_daily', 'circuit_breaker')
    op.drop_column('energy_consume_daily', 'addr')
    op.drop_column('energy_consume_monthly', 'circuit_breaker')
    op.drop_constraint('energy_consume_monthly_ibfk_1', 'energy_consume_monthly', type_='foreignkey')
    # op.drop_table('circuit_breakers')
    op.drop_table('ir_count')
    op.add_column('energy_consume_daily', sa.Column('box_id', sa.Integer(), nullable=True))
    op.add_column('energy_consume_daily', sa.Column('s3_fc20_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'energy_consume_daily', 's3_fc20', ['s3_fc20_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'energy_consume_daily', 'mantunci_box', ['box_id'], ['id'], ondelete='CASCADE')
    op.add_column('energy_consume_monthly', sa.Column('box_id', sa.Integer(), nullable=True))
    op.add_column('energy_consume_monthly', sa.Column('s3_fc20_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'energy_consume_monthly', 's3_fc20', ['s3_fc20_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'energy_consume_monthly', 'mantunci_box', ['box_id'], ['id'])
    op.drop_column('energy_consume_monthly', 'addr')
    op.add_column('switch_status', sa.Column('switch_id', sa.Integer(), nullable=True))
    op.drop_constraint('switch_status_ibfk_1', 'switch_status', type_='foreignkey')
    op.create_foreign_key(None, 'switch_status', 'switches', ['switch_id'], ['id'], ondelete='CASCADE')
    op.drop_column('switch_status', 'load')
    op.drop_column('switch_status', 'sensor_id')
    op.add_column('switches', sa.Column('level', sa.SmallInteger(), nullable=True))
    op.add_column('switches', sa.Column('locator_id', sa.Unicode(length=50), nullable=True))
    op.add_column('switches', sa.Column('switch_panel_id', sa.Integer(), nullable=True))
    op.drop_constraint('switches_ibfk_4', 'switches', type_='foreignkey')
    op.drop_constraint('switches_ibfk_2', 'switches', type_='foreignkey')
    op.drop_constraint('switches_ibfk_1', 'switches', type_='foreignkey')
    op.drop_constraint('switches_ibfk_3', 'switches', type_='foreignkey')
    op.create_foreign_key(None, 'switches', 'switch_panel', ['switch_panel_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'switches', 'locators', ['locator_id'], ['internal_code'], ondelete='SET NULL')
    op.drop_column('switches', 'lux_id')
    op.drop_column('switches', 'locator')
    op.drop_column('switches', 'ir_id')
    op.drop_column('switches', 'aqi_id')
    # ### end Alembic commands ###

    op.create_foreign_key(None, 'mantunci_box', 'box_alarms', ['latest_alarm_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 's3_fc20', 's3_fc20_records', ['latest_record_id'], ['id'], ondelete='SET NULL')


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switches', sa.Column('aqi_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('switches', sa.Column('ir_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('switches', sa.Column('locator', mysql.VARCHAR(length=50), nullable=True))
    op.add_column('switches', sa.Column('lux_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'switches', type_='foreignkey')
    op.drop_constraint(None, 'switches', type_='foreignkey')
    op.create_foreign_key('switches_ibfk_3', 'switches', 'aqi_sensors', ['aqi_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('switches_ibfk_1', 'switches', 'locators', ['locator'], ['internal_code'], ondelete='SET NULL')
    op.create_foreign_key('switches_ibfk_2', 'switches', 'ir_sensors', ['ir_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('switches_ibfk_4', 'switches', 'lux_sensors', ['lux_id'], ['id'], ondelete='SET NULL')
    op.drop_column('switches', 'switch_panel_id')
    op.drop_column('switches', 'locator_id')
    op.drop_column('switches', 'level')
    op.add_column('switch_status', sa.Column('sensor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('switch_status', sa.Column('load', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'switch_status', type_='foreignkey')
    op.create_foreign_key('switch_status_ibfk_1', 'switch_status', 'switches', ['sensor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('switch_status', 'switch_id')
    op.alter_column('switch_flag', 'touch',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('switch_flag', 'manual',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('switch_flag', 'latest_status',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.alter_column('ir_sensor_status', 'status',
               existing_type=sa.BOOLEAN(),
               type_=mysql.TINYINT(display_width=1),
               existing_nullable=True)
    op.add_column('energy_consume_monthly', sa.Column('addr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('energy_consume_monthly', sa.Column('circuit_breaker', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'energy_consume_monthly', type_='foreignkey')
    op.drop_constraint(None, 'energy_consume_monthly', type_='foreignkey')
    op.create_foreign_key('energy_consume_monthly_ibfk_1', 'energy_consume_monthly', 'circuit_breakers', ['circuit_breaker'], ['id'])
    op.drop_column('energy_consume_monthly', 's3_fc20_id')
    op.drop_column('energy_consume_monthly', 'box_id')
    op.add_column('energy_consume_daily', sa.Column('addr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('energy_consume_daily', sa.Column('circuit_breaker', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'energy_consume_daily', type_='foreignkey')
    op.drop_constraint(None, 'energy_consume_daily', type_='foreignkey')
    op.create_foreign_key('energy_consume_daily_ibfk_1', 'energy_consume_daily', 'circuit_breakers', ['circuit_breaker'], ['id'], ondelete='CASCADE')
    op.drop_column('energy_consume_daily', 's3_fc20_id')
    op.drop_column('energy_consume_daily', 'box_id')
    op.create_table('latest_alarms',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('circuit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('circuit_alarm_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['circuit_alarm_id'], ['circuit_alarms.id'], name='latest_alarms_ibfk_1', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuit_breakers.id'], name='latest_alarms_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_latest_alarms_circuit_id', 'latest_alarms', ['circuit_id'], unique=False)
    op.create_table('circuit_records',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('circuit_breaker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('addr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('validity', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('enable_netctr', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('oc', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('online', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('total_power', mysql.FLOAT(), nullable=True),
    sa.Column('mxgg', mysql.FLOAT(), nullable=True),
    sa.Column('mxgl', mysql.FLOAT(), nullable=True),
    sa.Column('line_type', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('spec', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('control', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('visibility', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('alarm', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('gLd', mysql.FLOAT(), nullable=True),
    sa.Column('gA', mysql.FLOAT(), nullable=True),
    sa.Column('gT', mysql.FLOAT(), nullable=True),
    sa.Column('gV', mysql.FLOAT(), nullable=True),
    sa.Column('gW', mysql.FLOAT(), nullable=True),
    sa.Column('gPF', mysql.FLOAT(), nullable=True),
    sa.Column('aA', mysql.FLOAT(), nullable=True),
    sa.Column('aT', mysql.FLOAT(), nullable=True),
    sa.Column('aV', mysql.FLOAT(), nullable=True),
    sa.Column('aW', mysql.FLOAT(), nullable=True),
    sa.Column('aPF', mysql.FLOAT(), nullable=True),
    sa.Column('bA', mysql.FLOAT(), nullable=True),
    sa.Column('bT', mysql.FLOAT(), nullable=True),
    sa.Column('bV', mysql.FLOAT(), nullable=True),
    sa.Column('bW', mysql.FLOAT(), nullable=True),
    sa.Column('bPF', mysql.FLOAT(), nullable=True),
    sa.Column('cA', mysql.FLOAT(), nullable=True),
    sa.Column('cT', mysql.FLOAT(), nullable=True),
    sa.Column('cV', mysql.FLOAT(), nullable=True),
    sa.Column('cW', mysql.FLOAT(), nullable=True),
    sa.Column('cPF', mysql.FLOAT(), nullable=True),
    sa.Column('nA', mysql.FLOAT(), nullable=True),
    sa.Column('nT', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['circuit_breaker_id'], ['circuit_breakers.id'], name='circuit_records_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('ir_count',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('ir_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ir_id'], ['ir_sensors.id'], name='ir_count_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('circuit_alarms',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('circuit_breaker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('addr', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('node', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('info', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('type_number', mysql.SMALLINT(display_width=6), autoincrement=False, nullable=True),
    sa.Column('alarm_or_type', mysql.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['circuit_breaker_id'], ['circuit_breakers.id'], name='circuit_alarms_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('latest_circuit_record',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('circuit_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('circuit_record_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['circuit_id'], ['circuit_breakers.id'], name='latest_circuit_record_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['circuit_record_id'], ['circuit_records.id'], name='latest_circuit_record_ibfk_2', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_latest_circuit_record_circuit_id', 'latest_circuit_record', ['circuit_id'], unique=False)
    op.create_table('circuit_breakers',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('mac', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('name', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('phone', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('locator', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('room', mysql.VARCHAR(length=30), nullable=True),
    sa.Column('unit', mysql.VARCHAR(length=30), nullable=True),
    sa.ForeignKeyConstraint(['locator'], ['locators.internal_code'], name='circuit_breakers_ibfk_1', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_circuit_breakers_mac', 'circuit_breakers', ['mac'], unique=False)
    op.drop_table('switch_panel')
    op.drop_table('s3_fc20_records')
    op.drop_table('s3_fc20')
    op.drop_index(op.f('ix_mantunci_box_mac'), table_name='mantunci_box')
    op.drop_table('mantunci_box')
    op.drop_table('energy_consume_by_hour')
    op.drop_table('box_alarms')
    op.drop_table('auto_controllers')
    # ### end Alembic commands ###
