"""add type column to appear records

Revision ID: 673eaa1771e4
Revises: c1f4a5872905
Create Date: 2020-01-06 11:26:10.443580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '673eaa1771e4'
down_revision = 'c1f4a5872905'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appear_records', sa.Column('type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appear_records', 'type')
    # ### end Alembic commands ###
