"""add uni_alarms table

Revision ID: 715ccb6b1d73
Revises: 46ebceb73fbc
Create Date: 2019-12-19 14:39:28.389946

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '715ccb6b1d73'
down_revision = '46ebceb73fbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uni_alarms',
                    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'),
                              nullable=False),
                    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('internal_id', sa.Integer(), nullable=False),
                    sa.Column('external_id', sa.Unicode(length=30), nullable=True),
                    sa.Column('happen_time', sa.TIMESTAMP(), nullable=True),
                    sa.Column('alarm_group', sa.SmallInteger(), nullable=True),
                    sa.Column('alarm_code', sa.Integer(), nullable=True),
                    sa.Column('alarm_content', sa.Unicode(length=100), nullable=True),
                    sa.Column('room', sa.Unicode(length=10), nullable=True),
                    sa.Column('floor', sa.Integer(), nullable=True),
                    sa.Column('extra', sa.Unicode(length=200), nullable=True),
                    sa.Column('active', sa.SmallInteger(), nullable=True),
                    sa.PrimaryKeyConstraint('internal_id')
                    )
    op.alter_column('notification', 'title',
                    existing_type=mysql.VARCHAR(charset='utf8', length=400),
                    type_=sa.Unicode(length=50),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification', 'title',
                    existing_type=sa.Unicode(length=50),
                    type_=mysql.VARCHAR(charset='utf8', length=400),
                    existing_nullable=True)
    op.drop_table('uni_alarms')
    # ### end Alembic commands ###
