"""empty message

Revision ID: 80575bc6e9d3
Revises: 2e4cc79a1dce
Create Date: 2019-08-23 17:59:48.666703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '80575bc6e9d3'
down_revision = '2e4cc79a1dce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'switches', 'switch_status', ['latest_record_id'], ['id'], ondelete='SET NULL')


