"""empty message

Revision ID: 81c74be661a7
Revises: 2e6567159881
Create Date: 2019-09-25 11:05:30.621149

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '81c74be661a7'
down_revision = '2e6567159881'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('acs_records', sa.Column('event_id', sa.Unicode(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('acs_records', 'event_id')
    # ### end Alembic commands ###
