"""empty message

Revision ID: 8f6b120c5c5d
Revises: 55d9dea26d96
Create Date: 2019-08-29 20:18:50.602766

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f6b120c5c5d'
down_revision = '55d9dea26d96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'relay_status', 'relay', ['relay_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'relay_id', type_='foreignkey')
    # ### end Alembic commands ###
