"""add active to appear_records

Revision ID: 9f7ce1a0a181
Revises: 507273553149
Create Date: 2020-01-13 10:36:31.040976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7ce1a0a181'
down_revision = '507273553149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appear_records', sa.Column('active', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appear_records', 'active')
    # ### end Alembic commands ###
