"""empty message

Revision ID: a3c9e04f9802
Revises: cb1316f31d05
Create Date: 2019-07-19 11:49:32.832186

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a3c9e04f9802'
down_revision = 'cb1316f31d05'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracking_devices', sa.Column('latest_acs_record_id',
                                                sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tracking_devices', 'acs_records', 
                          ['latest_acs_record_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tracking_devices', type_='foreignkey')
    op.drop_column('tracking_devices', 'latest_acs_record_id')
    # ### end Alembic commands ###
