"""empty message

Revision ID: a40b114168b5
Revises: a3c9e04f9802
Create Date: 2019-07-19 17:22:24.387538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a40b114168b5'
down_revision = 'a3c9e04f9802'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elevators', sa.Column('latest_record_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'elevators', 'elevator_status', ['latest_record_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'elevators', type_='foreignkey')
    op.drop_column('elevators', 'latest_record_id')
    # ### end Alembic commands ###
