"""empty message

Revision ID: bb3f808b6fd5
Revises: 4bea87eab022
Create Date: 2019-12-02 17:58:36.706588

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bb3f808b6fd5'
down_revision = '4bea87eab022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ir_sensors', sa.Column('status', sa.SmallInteger(), nullable=True))
    op.drop_constraint('ir_sensors_ibfk_3', 'ir_sensors', type_='foreignkey')
    op.drop_column('ir_sensors', 'latest_record_id')
    op.drop_table('ir_sensor_status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ir_sensors', 'status')
    op.create_table('ir_sensor_status',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), nullable=True),
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('sensor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('value', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['ir_sensors.id'], name='ir_sensor_status_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.add_column('ir_sensors', sa.Column('latest_record_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('ir_sensors_ibfk_3', 'ir_sensors', 'ir_sensor_status', ['latest_record_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
