"""add level to Unialarm

Revision ID: c30c34e0c006
Revises: 37c51c7deec0
Create Date: 2020-01-07 16:59:22.338633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c30c34e0c006'
down_revision = '37c51c7deec0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uni_alarms', sa.Column('level', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uni_alarms', 'level')
    # ### end Alembic commands ###
