"""add door table

Revision ID: caffaf31fe2c
Revises: 67fe14066bdd
Create Date: 2019-12-08 14:52:27.558541

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'caffaf31fe2c'
down_revision = '67fe14066bdd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('door',
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('door_index_code', sa.Unicode(length=100), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('room_no_internal', sa.Unicode(length=100), nullable=True),
    sa.Column('room_no_external', sa.Unicode(length=100), nullable=True),
    sa.Column('desc', sa.Unicode(length=100), nullable=True),
    sa.PrimaryKeyConstraint('door_index_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('door')
    # ### end Alembic commands ###
