"""empty message

Revision ID: eccae84828cb
Revises: c3abbbd81271
Create Date: 2019-08-26 10:13:32.367538

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'eccae84828cb'
down_revision = 'c3abbbd81271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('switch_panel', sa.Column('addr_no', sa.Integer(), nullable=True))
    op.add_column('switch_panel', sa.Column('batch_no', sa.Integer(), nullable=True))
    op.drop_index('ix_switch_panel_device_index_code', table_name='switch_panel')
    op.drop_column('switch_panel', 'device_index_code')
    # ### end Alembic commands ###
