"""empty message

Revision ID: edd2e8b01c23
Revises: eccae84828cb
Create Date: 2019-08-28 22:35:47.907445

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'edd2e8b01c23'
down_revision = 'eccae84828cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('relay', 'control_type')
    op.add_column('switches', sa.Column('control_type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


