"""empty message

Revision ID: f83f94b3ee11
Revises: a40b114168b5
Create Date: 2019-07-19 17:25:51.979312

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f83f94b3ee11'
down_revision = 'a40b114168b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('elevator_status',
                  sa.Column('direction',
                            sa.SmallInteger(),
                            nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('elevator_status', 'direction')
    # ### end Alembic commands ###
